default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  adapter: postgis
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("DEV_POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DEV_POSTGRES_PORT", 5433) %>
  username: <%= ENV.fetch("DEV_POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("DEV_POSTGRES_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("DEV_POSTGRES_DB", "entelequia") %>

test:
  <<: *default
  host: <%= ENV.fetch("DEV_POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DEV_POSTGRES_PORT", 5433) %>
  username: <%= ENV.fetch("DEV_POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("DEV_POSTGRES_PASSWORD", "postgres") %>
  database: entelequia_test

production:
  adapter: postgis
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("PROD_POSTGRES_HOST") %>
  port: <%= ENV.fetch("PROD_POSTGRES_PORT") %>
  username: <%= ENV.fetch("PROD_POSTGRES_USER") %>
  password: <%= ENV.fetch("PROD_POSTGRES_PASSWORD") %>
  database: <%= ENV.fetch("PROD_POSTGRES_DB") %>

queue:
  <<: *default
  host: <%= ENV.fetch("PROD_POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PROD_POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("PROD_POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("PROD_POSTGRES_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("PROD_POSTGRES_DB", "entelequia_production") %>

cache:
  <<: *default
  host: <%= ENV.fetch("PROD_POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PROD_POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("PROD_POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("PROD_POSTGRES_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("PROD_POSTGRES_DB", "entelequia_production") %>